### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by kaylabrinkerhoff** [drexnexlo/web-iv-portfolio-site#1]
I would maybe organize your images folder better. Like adding img-name.jpg just so it's more consistent. Also some of your file names in your img file do not have hyphens. You also have images in your assets folder in your js folder which is a little confusing. There is a fonts folder in your slick js folder. 
Below Satisfactory.

**Comment by e-m-durham** [comment]
Remove any unused files
All lowercase chicago.JPG should be chicago.jpg
red-box.png instead of redbox.png

**Comment by e-m-durham** [comment]
Prefixing your images to aid in organization of your img folder.
