### ISSUE TITLE
UX- Mobile Images-Project Page

### ISSUE THREAD

**Issue by slaterjen** [drexnexlo/web-iv-portfolio-site#11]
Your mobile images are really big on your project page. On mobile the image would take up the entire screen, which might be confusing for the user. Consider maybe changing the size of the image for mobile screen.

**Comment by e-m-durham** [comment]
I can see that first image being so big on mobile causing potential confusion, but I think once the user is scrolling there wouldn't be much of a problem using very vertical images.
