### ISSUE TITLE
 HTML File Cleanliness of Code

### ISSUE THREAD

**Issue by am548726** [drexnexlo/web-iv-portfolio-site#13]
- Apply source formatting to your html file so we can easily see the hierarchy of your nested elements
- There multiple lines where your image tag needs an alt
- On line 133 there is a closed section tag that is missing its opening tag
- Check validation to fix your errors

<img width="1440" alt="screen shot 2015-11-13 at 3 02 14 pm" src="https://cloud.githubusercontent.com/assets/12190915/11157547/b4fde0ca-8a17-11e5-8a9c-07ad2a796c6c.png">

**Comment by am548726** [comment]
Cleanliness of Code Grade
Below Satisfactory

**Comment by e-m-durham** [comment]
Don't use uppercase in your markup, control that with CSS.
<img width="449" alt="screen shot 2015-11-14 at 10 30 37 am" src="https://cloud.githubusercontent.com/assets/2342978/11164597/c3b885cc-8aba-11e5-895b-89ebafe3a1ef.png">
