### ISSUE TITLE
CSS File Cleanliness of Code

### ISSUE THREAD

**Issue by am548726** [drexnexlo/web-iv-portfolio-site#15]
- Drew please apply source formatting
- To fix your lines 47–49 you need to add the transform element after line 49
- You can apply shorthand properties to reduce your amount of lines needed in css for example on line 56 you can use the padding shorthand
- On line 5 there is a parse error you can delete it to fix it
  <img width="1440" alt="screen shot 2015-11-13 at 3 08 17 pm" src="https://cloud.githubusercontent.com/assets/12190915/11157697/83ff11e6-8a18-11e5-8bab-6a37a362ec02.png">

<img width="1440" alt="screen shot 2015-11-13 at 3 08 24 pm" src="https://cloud.githubusercontent.com/assets/12190915/11157698/88d73ba8-8a18-11e5-9cc9-0cc2797cb00a.png">

**Comment by e-m-durham** [comment]
Yes, take some time to format but also to organize your file a little bit more meaningfully. Comment consistently, etc.

**Comment by e-m-durham** [comment]
Begin a table of contents for your stylesheet.
